### ISSUE TITLE
Possible warning saying wordpress isnt hooked up correctly?

### ISSUE THREAD

**Issue by maxdub** [BradyEdgar94/create-awesome-react-app#2]
<img width="1220" alt="Screen Shot 2019-10-26 at 11 45 43 PM" src="https://user-images.githubusercontent.com/8998665/67629362-cea99780-f84a-11e9-99f8-ded4bbe33fb4.png">

×
FetchError: invalid json response body at http://portfolio.dev/wp-json/wp/v2/pages?slug=home reason: Unexpected token Y in JSON at position 0
▶ 2 stack frames were collapsed.
async Object.getPageData
./lib/api.js:8
   5 | site: {
   6 |   async getPageData (slug) {
   7 |     const response = await fetch(`${API}/pages?slug=${slug}`)
>  8 |     const data = await response.json()
     | ^   9 | 
  10 |     return data[0]
  11 |   },
View compiled
async Function.getInitialProps
./containers/Home.js:7
   4 | 
   5 | class Container extends React.Component {
   6 |   static async getInitialProps () {
>  7 |     const [ page, headerMenu, footerMenu ] = await Promise.all([
   8 |       api.site.getPageData('home'),
   9 |       api.site.getHeaderMenu(),
  10 |       api.site.getFooterMenu()
View compiled
async loadGetInitialProps
./node_modules/next/dist/next-server/lib/utils.js:50
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by BradyEdgar94** [comment]
When seeing `Unexpected token Y in JSON at position 0` it will mean that something is not right with your API request to the WordPress CMS. Double-check that URL http://portfolio.dev/wp-json is actually working and you can see a response, if not there is likely something wrong with your hostname.

Double-check you updated MAMP PRO or your host configurations to point http://portfolio.dev to the api folder of your project.
